model_args:
  model_name: 'resnet18'
  pretrained: true
  num_outputs: 8
  weights: /home/student03/work/Artyom/pretrained/resnet18-5c106cde.pth

losses:
  - name: 'mae'
    loss_fn: 'torch.nn.L1Loss'
    weight: 1.0
    loss_kwargs:
      reduction: mean

optimizer: 'torch.optim.AdamW'
optimizer_kwargs:
  lr: 5e-3
  weight_decay: 1e-3

scheduler: 'torch.optim.lr_scheduler.ReduceLROnPlateau'
scheduler_kwargs:
  mode: min
  factor: 0.1
  patience: 5
  threshold: 0.0001

checkpoint_callback:
  monitor_mode: min
  monitor_metric: val_mae
  verbose: true