train:
  transform:
    __class_fullname__: Compose
    transforms:
      - __class_fullname__: Resize
        height: &height_ 512
        width: &width_ 512
      - __class_fullname__: albumentations.augmentations.geometric.transforms.HorizontalFlip
        p: 0.5
      - __class_fullname__: ToTensorV2
        always_apply: true
        transpose_mask: true

val:
  transform:
    __class_fullname__: Compose
    transforms:
      - __class_fullname__: Resize
        height: *height_
        width: *width_
      - __class_fullname__: ToTensorV2
        always_apply: true
        transpose_mask: true